adjective = input("Please enter an adjective:")
noun = input("Please enter an noun:")
verb = input("Please enter an verb ending in -ed:")
print("Your MadLib:")
print("The",adjective,noun,verb,"over the lazy brown dog")